repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run pytest tests/ -v --cov=tasks --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        types: [] # if types is ['dockerfile'], then pre-commit will never pass Containerfile to hadolint
        files: Containerfile

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]
