# yaml-language-server: $schema=metadata.schema.json
---
argocd:
  description: >
    Declarative Continuous Deployment for Kubernetes

  download_url: >
    https://github.com/argoproj/argo-cd/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/argoproj/argo-cd
  license: APACHE-2.0
  version: 3.4.2
  sha256: d4cb1ac8002baab8afaca2da3de597b613df8459074bc7c6d96dc95161c2a33f
asdf:
  description: >
    Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/asdf-vm/asdf
  license: MIT
  version: 0.19.0
bd:
  description: >
    Beads - A memory upgrade for your coding agent

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/beads_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/steveyegge/beads
  license: MIT
  version: 1.0.4
  sha256: 643e602e27f666c8726abff0f22001e2b5883988fa960204bde20a3129d448a5
cr:
  description: >
    CLI tool for linting and testing Helm charts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/chart-releaser_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/helm/chart-releaser
  license: APACHE-2.0
  version: 1.8.1
  sha256: 834046b27b00cd6ba451326875c1937d4f2b671063c2053e031434ade73002b5
ct:
  description: >
    Hosting Helm Charts via GitHub Pages and Releases

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/chart-testing_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/helm/chart-testing
  license: APACHE-2.0
  version: 3.14.0
  sha256: d16f0583616885423826241164ce1f6589c6fe5332fa74f374ebd2bd3cb3fe1f
ctlptl:
  description: >
    Making local Kubernetes clusters fun and easy to set up

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}.{{version}}.{{os}}.{{rust_arch}}.tar.gz

  repo_url: https://github.com/tilt-dev/ctlptl
  license: APACHE-2.0
  version: 0.9.3
  sha256: c5130e27e367750f7d813558720921391233c98f35d6c3221793890b872769db
doctl:
  description: >
    A command line tool for DigitalOcean services

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/digitalocean/doctl
  license: APACHE-2.0
  version: 1.159.0
  sha256: 0f90be5397ccb82b1ad66ab9ebb356ee5446eb128963331aa953ef4e43693927
exo:
  description: >
    Command-line tool for everything at Exoscale: compute, storage, dns.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/exoscale-cli_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/exoscale/cli
  license: APACHE-2.0
  version: 1.94.2
  sha256: 84f6590679d979b71bfdbcb4ed8b4f14b2dc3176ec721eacf3358c37a7a3dd28
flux:
  description: >
    Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/fluxcd/flux2
  license: APACHE-2.0
  version: 2.8.7
  sha256: 493a8df42bf89f8481f03afb44b6f4801a76ec0f0b9233042487d0cb5c6cf4e3
helm-docs:
  description: >
    A tool for automatically generating markdown documentation for helm charts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os|capitalize}}_{{rust_arch}}.tar.gz

  repo_url: https://github.com/norwoodj/helm-docs
  license: GPL-3.0
  version: 1.14.2
  sha256: a8cf72ada34fad93285ba2a452b38bdc5bd52cc9a571236244ec31022928d6cc
k3d:
  description: >
    Little helper to run CNCF's k3s in Docker

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}{{ ".exe" if os == "windows" else ""}}

  repo_url: https://github.com/k3d-io/k3d
  license: MIT
  version: 5.8.3
  sha256: dbaa79a76ace7f4ca230a1ff41dc7d8a5036a8ad0309e9c54f9bf3836dbe853e
k3s:
  description: >
    Lightweight Kubernetes

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}{{ "-%s" | format(arch) if arch != "amd64" else "" }}

  repo_url: https://github.com/k3s-io/k3s
  license: APACHE-2.0
  version: 1.36.0+k3s1
  sha256: efa953454c8f7bf8d9d35c2dad2a76c9bdaac6860d60361629a3a2719009876b
k9s:
  description: >
    🐶 Kubernetes CLI To Manage Your Clusters In Style!

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/k9s_Linux_{{arch}}.tar.gz

  repo_url: https://github.com/derailed/k9s
  license: APACHE-2.0
  version: 0.50.18
  sha256: 0b697ed4aa80997f7de4deeed6f1fba73df191b28bf691b1f28d2f45fa2a9e9b
kind:
  description: >
    A tool for running local Kubernetes clusters using Docker

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/kubernetes-sigs/kind
  license: MIT
  version: 0.31.0
  sha256: eb244cbafcc157dff60cf68693c14c9a75c4e6e6fedaf9cd71c58117cb93e3fa
kustomize:
  description: >
    Customization of kubernetes YAML configurations

  download_url: >
    {{repo_url}}/releases/download/{{name}}/v{{version}}/{{name}}_v{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/kubernetes-sigs/kustomize
  license: APACHE-2.0
  version: 5.8.1
  sha256: 029a7f0f4e1932c52a0476cf02a0fd855c0bb85694b82c338fc648dcb53a819d
opencode:
  description: >
    The open source coding agent.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-linux-x64.tar.gz

  repo_url: https://github.com/anomalyco/opencode
  license: MIT
  version: 1.15.3
  sha256: f8ae8678c9bccdbaf99777f36ff2d5efe689d473384f2e94b84d6cda256d2540
packer:
  description: >
    Packer is a tool for creating identical machine images for multiple platforms from a single source configuration.

  download_url: >
    https://releases.hashicorp.com/{{name}}/{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/hashicorp/packer
  license: MPL-2.0
  version: 1.15.3
  sha256: 9ed712c9a8f223c7985d7d21c6b65744bf1c66b8aca333232b96f5ae3fd9c90d
shellcheck:
  description: >
    ShellCheck, a static analysis tool for shell scripts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}.{{os|capitalize}}.{{rust_arch}}.tar.xz

  repo_url: https://github.com/koalaman/shellcheck
  license: GPL-3.0
  version: 0.11.0
  sha256: 8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198
skaffold:
  description: >
    Easy and Repeatable Kubernetes Development

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/GoogleContainerTools/skaffold
  license: APACHE-2.0
  version: 2.20.0
  sha256: 8794026e7f0c2fb04c44ebc6a8f4f446a7a68dde8f8868ac5b701903b7973e19
solc:
  description: >
    Solidity, the Smart Contract Programming Language

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-static-{{os}}

  repo_url: https://github.com/ethereum/solidity
  license: GPL-3.0
  version: 0.8.35
  sha256: fa8ac9a32d301ad023a36ee5a29f8e291fe3200c60244e43c142539e82a617f4
rtk:
  description: >
    High-performance CLI proxy that reduces LLM token consumption by 60-90% on common dev commands

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{rust_arch}}-{{ "apple-darwin" if os == "darwin" else "unknown-linux-musl" if rust_arch == "x86_64" else "unknown-linux-gnu" }}.tar.gz

  repo_url: https://github.com/rtk-ai/rtk
  license: MIT
  version: 0.40.0
  sha256: a75d210a445874106bc16da2b4efba01d36d297afa33ec134728f2d5f42ef5af
starship:
  description: >
    ☄🌌️ The minimal, blazing-fast, and infinitely customizable prompt for any shell!

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{rust_arch}}-unknown-{{os}}-gnu.tar.gz

  repo_url: https://github.com/starship/starship
  license: ICS
  version: 1.25.1
  sha256: 4488c11ca632327d1f1f16fb2f102c0646094c35479cd5435991385da43c61ac
terraform:
  description: >
    Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.

  download_url: >
    https://releases.hashicorp.com/{{name}}/{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/hashicorp/terraform
  license: Business Source License v1.1 https://www.hashicorp.com/bsl
  version: 1.15.3
  sha256: c3d4b579064745a5f7e918125db23b12ba52a8a7287adb9f32c49d637e02e3bf
terraform-docs:
  description: >
    Generate docs from terraform modules

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/segmentio/terraform-docs
  license: MIT
  version: 0.24.0
  sha256: 9005daf969de0b50134493a2c00078b49f5f5b39d021cda7c89bf4d4f3d776d3
terragrunt:
  description: >
    Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{os}}_{{arch}}

  repo_url: https://github.com/gruntwork-io/terragrunt
  license: MIT
  version: 1.0.4
  sha256: 387509aa15d3f38a93d0888ace2bd67c3e5eea841e1f4d585ea2174d566f35e9
tflint:
  description: >
    A Pluggable Terraform Linter

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  version: 0.62.1
  sha256: c004ec45ade3caf87cd4089feb1d2af9f7df57b13140a36df8a63c0a8cc69f14
tilt:
  description: >
    Define your dev environment as code. For microservice apps on Kubernetes.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}.{{version}}.{{os}}.{{rust_arch}}.tar.gz

  repo_url: https://github.com/tilt-dev/tilt
  license: APACHE-2.0
  version: 0.37.3
  sha256: e90bc6cf70882bc7579d8174a27cab2de0284612ec7339e4b32f669cd5de4e5c
