# yaml-language-server: $schema=metadata.schema.json
---
argocd:
  description: >
    Declarative Continuous Deployment for Kubernetes

  download_url: >
    https://github.com/argoproj/argo-cd/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/argoproj/argo-cd
  license: APACHE-2.0
  version: 3.4.5
  sha256: 23303f05a58c1e041324d5645b0f9d6ea338b16bbf32f4a24508f388fcf9f9c0
asdf:
  description: >
    Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/asdf-vm/asdf
  license: MIT
  version: 0.20.0
bd:
  description: >
    Beads - A memory upgrade for your coding agent

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/beads_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/steveyegge/beads
  license: MIT
  version: 1.1.0
  sha256: b0f3dd607c3fb989ee08d0a6854fba80d0402971eb108f9af6170bc14d491a34
cr:
  description: >
    CLI tool for linting and testing Helm charts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/chart-releaser_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/helm/chart-releaser
  license: APACHE-2.0
  version: 1.8.1
  sha256: 834046b27b00cd6ba451326875c1937d4f2b671063c2053e031434ade73002b5
crush:
  description: >
    Glamourous agentic coding for all

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os|capitalize}}_{{ "x86_64" if arch == "amd64" else arch }}.tar.gz

  repo_url: https://github.com/charmbracelet/crush
  license: FSL-1.1-MIT
  version: 0.84.1
  sha256: 14754490a649a1d4d013558fb810ca896457f3c6534a4d59e70709f73282ad76
ct:
  description: >
    Hosting Helm Charts via GitHub Pages and Releases

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/chart-testing_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/helm/chart-testing
  license: APACHE-2.0
  version: 3.14.0
  sha256: d16f0583616885423826241164ce1f6589c6fe5332fa74f374ebd2bd3cb3fe1f
ctlptl:
  description: >
    Making local Kubernetes clusters fun and easy to set up

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}.{{version}}.{{os}}.{{rust_arch}}.tar.gz

  repo_url: https://github.com/tilt-dev/ctlptl
  license: APACHE-2.0
  version: 0.9.4
  sha256: c63a1ec28e60bc3faf6becb76f53355c5cf5e0143dafdd27ad85db5584fa6b1e
direnv:
  description: >
    A shell extension that unloads and loads environment variables depending on the current directory.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}.{{os}}-{{arch}}

  repo_url: https://github.com/direnv/direnv
  license: MIT
  version: 2.37.1
  sha256: 1f1b93dd6f38523fde26dfac96151ef9d31a374e3005cd3345fb93555ae0c9b5
doctl:
  description: >
    A command line tool for DigitalOcean services

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/digitalocean/doctl
  license: APACHE-2.0
  version: 1.163.0
  sha256: 04413587db80236f80b02b586db094ffa94096891b14c2b4883b623ff3d59b48
exo:
  description: >
    Command-line tool for everything at Exoscale: compute, storage, dns.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/exoscale-cli_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/exoscale/cli
  license: APACHE-2.0
  version: 1.96.0
  sha256: 784783ae5ad6be5b5a60ded51c8c814f5370268338b17bfd556a412d384c84c4
flux:
  description: >
    Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/fluxcd/flux2
  license: APACHE-2.0
  version: 2.9.2
  sha256: 4092b367fd060097976fb7261601f79420ecf7266328417dfd8dfee27de0e6a3
golangci-lint:
  description: >
    Fast linters runner for Go

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/golangci/golangci-lint
  license: GPL-3.0
  version: 2.12.2
  sha256: 8df580d2670fed8fa984aac0507099af8df275e665215f5c7a2ae3943893a553
helm-docs:
  description: >
    A tool for automatically generating markdown documentation for helm charts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os|capitalize}}_{{rust_arch}}.tar.gz

  repo_url: https://github.com/norwoodj/helm-docs
  license: GPL-3.0
  version: 1.14.2
  sha256: a8cf72ada34fad93285ba2a452b38bdc5bd52cc9a571236244ec31022928d6cc
k3d:
  description: >
    Little helper to run CNCF's k3s in Docker

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}{{ ".exe" if os == "windows" else ""}}

  repo_url: https://github.com/k3d-io/k3d
  license: MIT
  version: 5.9.0
  sha256: 06d8f25bc3a971c4eb29e0ff08429b180402db0f4dec838c9eac427e296800a0
k3s:
  description: >
    Lightweight Kubernetes

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}{{ "-%s" | format(arch) if arch != "amd64" else "" }}

  repo_url: https://github.com/k3s-io/k3s
  license: APACHE-2.0
  version: 1.36.2+k3s1
  sha256: 65a55ec56c24eab44383086166ec620a491952b7e23941a49ddca6e8a4c4b4de
k9s:
  description: >
    🐶 Kubernetes CLI To Manage Your Clusters In Style!

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/k9s_Linux_{{arch}}.tar.gz

  repo_url: https://github.com/derailed/k9s
  license: APACHE-2.0
  version: 0.51.0
  sha256: c3752ad51a5a4015a113819c4eeb6e55a4d0e4b8e652494797532f6fc8161dd7
kind:
  description: >
    A tool for running local Kubernetes clusters using Docker

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/kubernetes-sigs/kind
  license: MIT
  version: 0.32.0
  sha256: 50030de23cf40a18505f20426f6a8506bedf13c6e509244bd1fa9463721b0f54
kustomize:
  description: >
    Customization of kubernetes YAML configurations

  download_url: >
    {{repo_url}}/releases/download/{{name}}/v{{version}}/{{name}}_v{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/kubernetes-sigs/kustomize
  license: APACHE-2.0
  version: 5.8.1
  sha256: 029a7f0f4e1932c52a0476cf02a0fd855c0bb85694b82c338fc648dcb53a819d
minikube:
  description: >
    Local Kubernetes, focusing on making it easy to learn and develop for Kubernetes.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}{{ ".exe" if os == "windows" else "" }}

  repo_url: https://github.com/kubernetes/minikube
  license: APACHE-2.0
  version: 1.38.1
  sha256: 099477eaf248bcb5bcea8ce78a2898e93ac01461c35189da1848c3de82ecd22e
opencode:
  description: >
    The open source coding agent.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-linux-x64.tar.gz

  repo_url: https://github.com/anomalyco/opencode
  license: MIT
  version: 1.18.2
  sha256: 97c95e004bb73d2039f957ea33be0635ea4e22b8dceaedf8f0983765950cf1b6
packer:
  description: >
    Packer is a tool for creating identical machine images for multiple platforms from a single source configuration.

  download_url: >
    https://releases.hashicorp.com/{{name}}/{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/hashicorp/packer
  license: MPL-2.0
  version: 1.15.4
  sha256: 15f97a6a99645c7d5308c609973b5280837b38e112beac413ccbce80da927cf1
rtk:
  description: >
    High-performance CLI proxy that reduces LLM token consumption by 60-90% on common dev commands

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{rust_arch}}-{{ "apple-darwin" if os == "darwin" else "unknown-linux-musl" if rust_arch == "x86_64" else "unknown-linux-gnu" }}.tar.gz

  repo_url: https://github.com/rtk-ai/rtk
  license: MIT
  version: 0.43.0
  sha256: ff8a1e7766496e175291a85aeca1dc97c9ff6df33e51e5893d1fbc78fea2a609
shellcheck:
  description: >
    ShellCheck, a static analysis tool for shell scripts

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}.{{os|capitalize}}.{{rust_arch}}.tar.xz

  repo_url: https://github.com/koalaman/shellcheck
  license: GPL-3.0
  version: 0.11.0
  sha256: 8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198
shfmt:
  description: >
    A shell parser, formatter, and interpreter with bash and zsh support; includes shfmt

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_v{{version}}_{{os}}_{{arch}}{{ ".exe" if os == "windows" else "" }}

  repo_url: https://github.com/mvdan/sh
  license: BSD-3-Clause
  version: 3.13.1
  sha256: fb096c5d1ac6beabbdbaa2874d025badb03ee07929f0c9ff67563ce8c75398b1
skaffold:
  description: >
    Easy and Repeatable Kubernetes Development

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{os}}-{{arch}}

  repo_url: https://github.com/GoogleContainerTools/skaffold
  license: APACHE-2.0
  version: 2.23.0
  sha256: c44fb83ec88a9ed2945f3326a6d6b78bb957354535f0efcf653413bcd0e9510d
solc:
  description: >
    Solidity, the Smart Contract Programming Language

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-static-{{os}}

  repo_url: https://github.com/ethereum/solidity
  license: GPL-3.0
  version: 0.8.36
  sha256: c8d35afdddc3cd2743ee88b8f25e0fecd16e2bdd5f2120f37e52cd9cc45ae0e6
sqlc:
  description: >
    Generate type-safe code from SQL

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/sqlc-dev/sqlc
  license: MIT
  version: 1.31.1
  sha256: 497ae4fcdfa64c5b0c311ffe4c2bd991e43991e82e5367792ed78bc2dca27354
starship:
  description: >
    ☄🌌️ The minimal, blazing-fast, and infinitely customizable prompt for any shell!

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-{{rust_arch}}-unknown-{{os}}-gnu.tar.gz

  repo_url: https://github.com/starship/starship
  license: ICS
  version: 1.26.0
  sha256: 321f0dd7af8340a5f2e6a8fec6538a04f617486f9ec70d878f91c09cd8deef22
task:
  description: >
    A task runner / build tool that aims to be simpler and easier to use than, for example, GNU Make.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{os}}_{{arch}}.tar.gz

  repo_url: https://github.com/go-task/task
  license: MIT
  version: 3.52.0
  sha256: 02c679ffae53dca791804847d78b31731615894e292948397c971c87ac9e95bd
terraform:
  description: >
    Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.

  download_url: >
    https://releases.hashicorp.com/{{name}}/{{version}}/{{name}}_{{version}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/hashicorp/terraform
  license: Business Source License v1.1 https://www.hashicorp.com/bsl
  version: 1.15.8
  sha256: d25ce7b6902013ad905db3d2eab0be4cd905887fe88b81a6171b8d5503c31f3d
terraform-docs:
  description: >
    Generate docs from terraform modules

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}-v{{version}}-{{os}}-{{arch}}.tar.gz

  repo_url: https://github.com/segmentio/terraform-docs
  license: MIT
  version: 0.24.0
  sha256: 9005daf969de0b50134493a2c00078b49f5f5b39d021cda7c89bf4d4f3d776d3
terragrunt:
  description: >
    Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{os}}_{{arch}}

  repo_url: https://github.com/gruntwork-io/terragrunt
  license: MIT
  version: 1.1.1
  sha256: 98b0400ba1ae27120adeeb98ba97e75eba0bab0b4cbd7b8bb148d4ed29e2f823
tflint:
  description: >
    A Pluggable Terraform Linter

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}_{{os}}_{{arch}}.zip

  repo_url: https://github.com/terraform-linters/tflint
  license: MPL 2.0
  version: 0.63.1
  sha256: 8441a7d97df20431f19c9b9d27ff4c63e308c964e86660bc7cc0cf7bbe0725e8
tilt:
  description: >
    Define your dev environment as code. For microservice apps on Kubernetes.

  download_url: >
    {{repo_url}}/releases/download/v{{version}}/{{name}}.{{version}}.{{os}}.{{rust_arch}}.tar.gz

  repo_url: https://github.com/tilt-dev/tilt
  license: APACHE-2.0
  version: 0.37.5
  sha256: 9efb56969c48ddea4adfb56a604b9ca5ed254924ddf140fc3e068a305cacf558
