name: Lint & Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Execute pre-commit
        uses: tankdonut/github-actions/actions/pre-commit@v1
        with:
          install_uv_deps: "true"
          uv_sync_args: "--group dev"
          extra_args: "--show-diff-on-failure --color=always --all-files"
