name: Prune GHCR Images

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "30 1 * * *" # Runs daily at 01:30 UTC

env:
  SEMVER_REGEX: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$

permissions:
  packages: write

jobs:
  prune:
    uses: tankdonut/github-actions/.github/workflows/prune-ghcr.yaml@v1
    with:
      packages: '["${{ github.event.repository.name }}"]'
      exclude-tags: "v.*,latest,${{ github.event.repository.default_branch }},${{ env.SEMVER_REGEX }}"
      keep-n-tagged: "10"
    secrets: inherit
